library("quanteda")
library("readtext")

donnees=readtext("https://github.com/eyssette/textes-philo/blob/main/data/textes.tsv?raw=true", text_field = "Texte", quote="", fill=TRUE)
corpusphilo=corpus(donnees)

dictionnaire <- dictionary(list(
  Éthique_et_Philosophie_Morale = c("éthique*", "bonheur*", "désir*", "plaisir*", "joie", "joy*", "bienheureu*", "contentement", "gaieté", "volupté*", "tentation*", "plénitude", "l'épanouissement", "d'épanouissement", "épanoui*", "s'épanoui*", "devoir*", "moral*", "heureu*", "se réaliser", "réalisation de soi", "joui*", "sage*", "béatitude", "vertu*", "bonté", "méchan*", "le mal", "le bien", "malheur*", "souffrance*", "souffr*", "douleur*", "besoin*", "satisfa*", "valeur*", "empathie", "compassion", "impératif catégorique", "l'impératif catégorique", "d'impératif catégorique", "impératifs catégoriques", "d'impératifs catégoriques", "utilitarisme*", "l'utilitarisme", "d'utilitarisme*", "déontologi*", "divertissement", "se divertir", "angoiss*", "l'angoisse", "d'angoisse", "pléonexie", "insatisfaction*", "d'insatisfaction*", "l'insatisfaction", "félicité", "maîtrise de soi", "vie bonne", "bonne vie", "care", "altruiste*", "altruisme", "l'altruisme", "d'altruisme", "génér*", "bienveillan*", "charit*", "égoïs*", "l'égoïs*", "d'égoïs*", "désintéress*", "superflu*", "vanité*", "conséquentiali*", "déontologi*", "la mort", "finitude", "mauvaise foi", "vic*", "innoncen*", "l'innoncen*", "d'innoncen*", "fin en soi", "mensonge", "spécisme", "antispécisme", "ce qui ne dépend pas de nous", "ce qui dépend de nous", "l'orgueil", "orgueil", "pêché", "bioéthique*", "l'exercice spirituel", "d'exercice spirituel", "exercices spirituels", "exercice spirituel", "d'exercices spirituels", "concentration sur le présent", "sérénité", "carpe diem", "gratitude", "négliger le présent", "autoréalisation", "l'autoréalisation", "d'autoréalisation", "blâme*", "mal agi", "remords", "égocentri*", "d'égocentri*","l'égocentri*", "écocentri*", "d'écocentri*","l'écocentri*", "hédon*"),
  Philosophie_de_l_esprit = c("conscien*", "inconscien*", "d'inconscien*", "l'inconscien*", "connaissance de soi", "réflexion*", "pensée*", "soi-même", "le moi", "du moi", "de moi", "le soi", "du soi", "de soi", "libre arbitre", "liberté de la volonté", "passion*", "émotion*", "subjectivité*", "phénoménologie", "phénoménal*", "le corps", "identité personnelle", "être soi", "être moi", "surmoi", "le ça", "image de soi", "psych*", "mémoire*", "souvenir*", "esprit", "l'esprit", "d'esprit", "intention*", "l'intention*", "d'intention*", "volont*", "personnel*", "personnalité", "intim*", "l'intim*", "d'intim*", "intériorité", "l'intériorité", "d'intériorité", "corporéité", "vécu", "affect*", "prédestination", "destin*", "fatal*", "déterminisme*", "cogito", "refoul*", "pulsions", "névro*" , "dire Je", "le Je", "la première personne", "connais-toi", "cognit*", "expérientiel", "qualia*", "motif*", "matérialisme", "physicalisme", "dualisme", "persona", "faiblesse de la volonté", "akrasie", "acrasie", "acratique", "d'acrasie", "l'acrasie", "d'akrasie", "l'akrasie", "opacité", "mental*", "l'attelage ailé", "attitudes réactives", "schizo*", "influence*", "spirit*", "l'âme", "âme", "la matière et l'esprit", "le corps et l'esprit", "être un corps", "avoir un corps", "corps propre", "identité narrative", "l'identité narrative", "d'identité narrative", "cogito, ergo sum", "cogito", "se mentir", "autobio*", "duperie de soi", "tromperie de soi", "introspecti*", "l'introspecti*", "d'introspecti*", "proto-Soi", "un soi", "un moi", "ce que je suis", "l'existence précède l'essence", "vrai moi", "ton moi", "ton être vrai", "d’auto-récits", "d’auto-récit", "l'auto-récit", "auto-récit*", "être-dans-le-monde", "dasein", "l'anatta", "anatta", "non-Soi", "existenti*", "choix", "se connaître"),
  Philosophie_de_la_culture = c("l'art", "art", "d'art", "arts", "artist*", "techn*", "humanité", "progrès", "histo*", "l'histo*", "d'histo*", "travail*", "esthéti*", "l'esthéti*", "d'esthéti*", "beau*", "musée*", "œuvre*", "cultur*", "civilis*", "littérature", "littéraire*", "sauvage*", "tradition*", "musique", "peinture", "peintre", "ethnocentr*", "l'ethnocentr*", "d'ethnocentr*", "goût", "beaux-arts", "génie", "talent", "inventi*", "créati*", "l'esprit objectif", "esprit objectif", "prohibition de l'inceste", "l'éducation", "éducation", "éduquer", "processus de civilisation", "processus de la civilisation", "tabous", "apprentissage", "pudeur", "barbar*", "anthropologi*", "ethnologi*", "sociocultur*", "socio-culturel*", "photographie*", "outil*", "l'outil", "d'outil*", "l'ordre humain", "l'animalité", "animalité", "d'animalité", "poésie*"),
  Philosophie_politique_et_sociale = c("politi*", "état*", "l'état*", "d'état*", "loi*", "juste*", "justice*", "injust*", "l'injust*", "d'injust*", "droit*", "gouvernement*", "guerre*","citoyen*", "liberté*", "force*", "puissance*", "pouvoir*", "autorité*", "l'autorité", "d'autorité", "paix", "tyrannie*", "obéir", "obéissance", "l'obéissance", "d'obéissance", "contrat*", "sanction*", "châtiment*", "talion", "punition*", "punir", "peuple*", "contrôle social", "pauvre*", "riche*", "ghetto*", "socia*", "société*", "échanges", "législa*", "légif*", "police", "oppress*", "coerci*", "inégalité*", "l'inégalité", "impôt*", "l'impôt", "violen*", "l'ordre social", "ordre social", "domin*", "publi*", "souverain*", "civiq*", "sujets", "communauté*", "institution*", "l'institution", "révolte*", "juridi*", "intérêts privés", "l'intérêt privé", "l'intérêt général", "biens communs", "bien commun", "délit", "désobéissan*", "l'exploitation", "d'exploitation", "travail aliéné", "travail aliénant", "propriété privée", "laïc*", "laïque*", "multicultur*", "libéralisme*", "anarchi*", "l'anarchi*", "d'anarchi*", "république*", "républic*", "patri*", "nation*", "d'égalitarisme", "l'égalitarisme", "égalitarisme", "bourgeois*", "marchandise", "l'économie", "économi*", "d'économi*", "idéologi*", "l'idéologi*", "d'idéologi*", "capital", "l'aliénation", "alién*", "d'aliénation*", "argent","l'argent", "d'argent", "lutte des classes", "redistribution*", "caste*", "corporation*", "collectif", "collectivité*", "amour-propre", "l'amour-propre", "d'amour-propre", "vengeance*", "l’État-providence", "welfare state", "régalien*", "allocation universelle", "d'allocation universelle", "l'allocation universelle", "revenu minimum", "revenu de base", "revenu", "mérit*", "équité", "l'équité", "d'équité", "totalita*", "contrainte*", "ressource*", "capabilité*", "distribut*", "cosmopol*", "stigmat*","démocrat*", "chef*", "volonté générale", "féminisme*", "élections", "vote*", "l'état de nature", "état de nature", "par la société", "non-domination", "vivre-ensemble", "sécul*", "accommodement*", "l'accommodement", "d'accommodement*", "liberté de conscience", "discrimination*", "règlement*", "sentiment d'appartenance", "séparation entre l'Église et l'État", "séparation de l'Église et de l'État", "loi de 1905", "judiciaire*", "despot*", "cité*", "rapports de production", "aristocra*", "user de la force", "leviathan", "léviathan"),
  Épistémologie_et_métaphysique = c("véri*", "le vrai", "raisonnement*", "science*","scientif*", "déduction*", "l'induction", "induction*", "perception*", "connai*", "connaître", "prédicti*", "physi*", "raison", "religi*", "sacré*", "divin*", "dieu*", "théol*", "théi*", "ration*", "magie", "magique*", "biologi*", "mathém*", "sociologi*", "lois physiques", "lois de la nature", "loi de la nature", "loi physique", "le réel", "la réalité", "métaphysi*", "l'épisté*", "épisté*", "l'expérimen*", "expérimen*", "la théorie", "galilée", "newton", "géométri*", "logi*", "certitude*", "croyan*", "croire", "foi", "l'athéisme", "d'athéisme", "athée*", "crédul*", "doute*", "faits", "savoirs", "le savoir", "l'entendement", "erreur*", "l'erreur", "abstraction", "apodict*", "l'apodict*", "d'apodict*", "empiri*", "l'empiri*", "d'empiri*", "l'a priori", "d'a priori", "syllogi*", "causalité", "les causes", "l'objectiv*", "d'objectiv*", "objectiv*","axiom*", "d'axiom*", "l'axiom*", "sciences de la nature", "science de la nature", "jugement", "a posteriori", "phénomène*", "intuit*", "l'intuit*", "d'intuit*", "arithmétique*", "d'arithmétique*", "l'arithmétique", "analytique", "l'univers-bloc", "d'univers-bloc", "univers-bloc", "relativité restreinte", "relativité générale", "relativisme", "scepti*", "trilemme d'agrippa", "l'éternalisme", "d'éternalisme", "éternalisme", "présentisme", "pythagor*" , "sophist*", "mesur*", "observat*", "l'observat*", "d'observat*", "anatom*", "l'anatom*", "astronom*", "l'astronom*", "d'astronom*", "révélation", "credo", "idées générales", "notion*", "falsif*", "réfut*", "démonstration", "démontr*", "factuel*", "tautologie*", "l'historien*", "faire de l'histoire", "superstit*", "l'être suprême"),
  Philosophie_du_langage=c("langage*", "langue*", "linguistique*", "grammaire", "Sapir-Whorf", "mot", "mots", "phrases", "communication*", "parole", "symbol*", "icône*", "signes", "discours", "énoncé*", "le signifiant", "du signifiant", "au signifié", "le signifié", "syntax*", "sons articulés", "parle*")
))


matrice=convert(dfm(corpusphilo, dictionary = dictionnaire, valuetype = "glob", case_insensitive = TRUE), "matrix")
basecomplete=cbind(donnees, matrice)
basecomplete=basecomplete[-c(1)]
basecomplete=basecomplete[c(2,3,1,4,5,6,7,8,9,10)]
write.table(basecomplete, file='test.tsv', quote=FALSE, sep='\t')
